field: 3ddcb807-d5ed-46a5-97ef-e4987bb9a122 # Episode Tracklist
fieldLayouts:
  01b92839-1c0b-4584-a193-690fdd0b6df3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b5239aff-3060-4188-bb73-be5d0212f4c3 # Song Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc26ef6f-e1f6-4a84-965b-9348cfe11bcd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 97244bbd-6b3a-432e-a3ab-55a3ea66f58f # Audio File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cda12e74-fca3-4104-8f04-37109d8cf780
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 2e7063c6-b2b6-430d-93aa-14c80d08d38e
        userCondition: null
fields:
  97244bbd-6b3a-432e-a3ab-55a3ea66f58f: # Audio File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audioFile
    instructions: null
    name: 'Audio File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:2173db2f-6479-4618-93b6-7268d73a8c6a' # Files
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:2173db2f-6479-4618-93b6-7268d73a8c6a' # Files
      restrictedLocationSubpath: 'episodes/{owner.slug}'
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add Audio File'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5239aff-3060-4188-bb73-be5d0212f4c3: # Song Title
    columnSuffix: alqdfpmf
    contentColumnType: text
    fieldGroup: null
    handle: songTitle
    instructions: null
    name: 'Song Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: coverSong
name: 'Cover Song'
sortOrder: 3
