field: a200069d-45d7-4a30-ac1e-d9272c0c3d4e # Timeline
fieldLayouts:
  5d4973e2-09e9-4d7b-84da-2dabb91a7ed3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b8b4f86-107d-461c-86bf-47d6d4b3669a # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32ae9aa3-da51-404b-9220-9fa877df1e4a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aa9b1096-ff2e-46f2-a476-6d112ac0facf # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9099d81c-45eb-4d2f-878a-45f05ab60395
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 52ae014e-2b8e-4f95-aded-848279031619 # Link To
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20e814d1-2381-4d5f-a20a-86d5ece2dbf5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 84d6a5da-c384-4483-b29d-b96099767e99 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fee62719-c764-4fa3-80d5-525686915b12
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 808a780a-2e88-4fda-bdf7-a26d112f58af
        userCondition: null
fields:
  0b8b4f86-107d-461c-86bf-47d6d4b3669a: # Date
    columnSuffix: percssao
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: null
    name: Date
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 30
      showDate: true
      showTime: false
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  52ae014e-2b8e-4f95-aded-848279031619: # Link To
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkTo
    instructions: null
    name: 'Link To'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:6b802ff4-dc8b-47a5-a650-2a7e4dd14e53' # Episodes
        - 'section:76ad2bc9-514a-434f-bc85-df4c60452ed4' # Library
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  84d6a5da-c384-4483-b29d-b96099767e99: # Tag
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: null
    name: Tag
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'taggroup:4bbad3aa-cf9c-4bb1-88e2-abbc411372bc' # Timeline
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  aa9b1096-ff2e-46f2-a476-6d112ac0facf: # Description
    columnSuffix: pgmxshbj
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: event
name: Event
sortOrder: 1
