fieldLayouts:
  a9013cd9-b63a-41a8-bfd2-e9322a33b584:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6a62c2e-a1f9-4290-b3f8-054d304f9be6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a200069d-45d7-4a30-ac1e-d9272c0c3d4e # Timeline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 022b7c7d-03dd-431c-a546-5b459bb63492
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac45e508-b391-4cc9-969c-98f12a0dcdd9
        userCondition: null
handle: timeline
hasTitleField: false
name: Timeline
section: 7421830d-d21d-4f02-ba04-28dd1e631f02 # Timeline
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
