columnSuffix: kkkxmawj
contentColumnType: string
fieldGroup: 39f5cac7-4bef-4a43-b917-4e68f50b886c # Album
handle: albumType
instructions: null
name: 'Album Type'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Studio
        -
          - value
          - studio
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Live Set'
        -
          - value
          - liveSet
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Episode Companion'
        -
          - value
          - episodeCompanion
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
